spring.application.name=backend

#spring.data.rest.base-path=/api

spring.datasource.url=jdbc:postgresql://ep-lucky-bonus-aoo82fn3-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_P1ZWLenIT9kx&sslmode=require&channelBinding=require
spring.datasource.username=${neondb_owner}
spring.datasource.password=${npg_P1ZWLenIT9kx}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



